version: "3"

services:

  ubuntu_vnc:
    build:
      args:
        update_source: "163"
        # http_proxy: http://192.168.0.37:707
        # https_proxy: http://192.168.0.37:707
      context: ./
      dockerfile: Dockerfile
    image: lianshufeng/ubuntu_vnc
    ports:
      - "5901:5901"
      - "6901:6901"
    privileged: true
    container_name: ubuntu_vnc
    restart: always
    environment:
      - VNC_PW=vncpassword
    
    
# http://192.168.80.128:6901/?password=vncpassword